volumes:
  pg-data: {}

services:
  db:
    image: postgres:16
    env_file:
      - envs/db/.env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
  server:
    image: phx-server
    build: 
      context: .
      dockerfile: compose/server/Dockerfile
      target: dev
    env_file:
      - envs/server/.env.dev
    ports:
      - "${SERVER_PORT:-4000}:4000"
    depends_on:
      - db
    volumes:
      - ./server:/server